name: Sync Shippo

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '9/20 * * * *' # Every 20th minute from 9 through 59 of every hour

jobs:
  sync_shippo:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Sync shippo
        run: |
          python main.py syncshippo
        env:
          CONFIG: ${{ secrets.CONFIG }}
